### ISSUE TITLE
Colors & themeing

### ISSUE THREAD

**Issue by rubiefawn** [rubiefawn/saffron#1]
Saffron needs a set of color variables with some reasonable defaults. These should supercede the `--col-<hue>[01]` variables. For example:

```css
:where(:root) {
  --col-blue-light: oklch(0.8 0.1 250);
  --col-blue-dark: oklch(60% 0.15 250);
  /* The dark variant should be used for light theme for contrast, and vice versa */
  --col-blue: light-dark(var(--col-blue-dark), var(--col-blue-light);
}
```

Currently the colors are just ripped straight from my terminal theme dotfiles, which isn't really suitable for general purpose web use.
